In [2]:
import numpy as np

# Elementwise Operations

**1. Basic Operations**


**with Scalars**



In [3]:
a = np.array([1, 2, 3, 4]) # creates an array

a + 1

array([2, 3, 4, 5])

In [4]:
print(a ** 2)

a ** 2

[ 1  4  9 16]


array([ 1,  4,  9, 16], dtype=int32)

**All arithmetic operates elementwise**

In [5]:
# a = [1, 2, 3, 4]

b = np.ones(4) + 1  # b = [2, 2, 2, 2]

a - b

array([-1.,  0.,  1.,  2.])

In [6]:
a * b

array([2., 4., 6., 8.])

In [7]:
# Matrix multiplication

c = np.diag([1, 2, 3, 4])

# Rows will be multiplied with columns
# There are 2 ways of multiplying matrix
print(c * c)  # way-1
print('***************')
print(c.dot(c))  # way-2

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


**Comparisions**

In [8]:
# Elementwise comparision

a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])

print(a == b)

print(np.equal(a, b))

[False  True False  True]
[False  True False  True]


In [9]:
a > b

array([False, False,  True, False])

In [10]:
# Array-wise comparisions
# Recommended way to compare arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [11]:
np.array_equal(a, c)

True

**Logical Operations**

In [12]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b) 

array([ True,  True,  True, False])

In [13]:
np.logical_and(a, b)

array([ True, False, False, False])

**Transcendental Functions**

In [14]:
a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [15]:
np.log(a)

C:\Users\ARMAN~1.ANS\AppData\Local\Temp/ipykernel_13468/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [16]:
np.exp(a)  # evaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

**Shape Mismatch**

In [17]:
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions


**Computing Sums**



In [18]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [19]:
# Sum by rows and by columns

x = np.array([[1, 1], [2, 2]])

x

array([[1, 1],
       [2, 2]])

In [20]:
x.sum(axis=0)  # columns first dimention

array([3, 3])

In [21]:
x.sum(axis=1)  # rows (second dimention)

array([2, 4])

**Other Reductions**

In [22]:
x = np.array([1, 3, 2])

x.min()

1

In [23]:
x.max()

3

In [24]:
x.argmin()  # Returns index of minimum element

0

In [25]:
x.argmax() # Returns index of maximum element

1

**Logical Operations**

In [26]:
np.all([True, True, False])

False

In [27]:
np.any([True, True, False])

True

In [28]:
# Note: can be used for array comparisions

a = np.zeros((50, 50))

np.any(a != 0)

False

In [29]:
np.all(a == a)

True

In [30]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

# [[True, True, True, True] & [True, True, True, True]].all()
# [True, True, True, True].all()

((a <= b) & (b <= c)).all()

True

**Statistics**

In [31]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

# Avg of elements in x
x.mean()

1.75

In [32]:
np.median(x)

1.5

In [33]:
# 1 is for row wise
# -1 and +1 both are same

# Middle elements of y (sort the element first)
np.median(y, axis=-1)  # last axis

array([2., 5.])

In [34]:
x.std()  # Full population standard dev.

0.82915619758885

**Example:**



Data in **population.txt** describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.



In [35]:
# Load data into numpy array object

# default type is 'float64'
# 77.4e3 means (77.4 * 10^3)
data = np.loadtxt('population.txt')

In [36]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.]])

In [37]:
# Transpose of a matrix
year, hares, lynxes, carrots = data.T  # columns to variables

print(year)

[1900. 1901. 1902. 1903. 1904.]


In [38]:
# The mean population over time

# data[take_all_the_rows, from_first_column_onwards]
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.]])

In [39]:
# Sample standard deviations

# computes by cols because of axis=0
populations.std(axis=0)

array([18599.39783972, 21422.41816416,  4135.98839457])

In [41]:
# Which 'species' has the highest population each year?

# operates row-wise 
# largest among (col1, col2, col3) for this operation
np.argmax(populations, axis=1)  # returns index of largest value

array([2, 2, 0, 0, 1], dtype=int64)