# NumPy Arrays

**python objects**

1. high-level number objects: integers, floating point
2. containers: list (costless insertion and append), dictionaries (fast lookup)

**Numpy provides:**

1. Extension package to python for multi-dimentional Arrays
2. closer to hardware (efficiency)
3. design for scientific computation (convenience)
4. Also known as Array oriented computing

**There are 2 ways of creating numpy array**

In [8]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


**Why it is useful:** Memory-efficient container that provides fast numerical operations

In [3]:
# Python lists
# from 0  to 999
L = range(1000)

# %timeit will display how much time it is taking for iterate every loop
%timeit [num**2 for num in L]

393 µs ± 25.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
# Numpy arrays
a = np.arange(1000)

# taking lesser time than python lists
%timeit a**2

2.28 µs ± 65.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 1. Creating Arrays

**1.1 Manual Construction of Arrays**

1. 1D array --> Vector
2. 2D array --> Matrix
3. nD array --> Tensor


In [15]:
# 1-D

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [16]:
# print dimentions

a.ndim

1

In [17]:
# print shape

a.shape

(4,)

In [18]:
# print size of array

len(a)

4

In [5]:
# 2-D, 3-D, ....

b = np.array([[0, 1, 2], [4, 5, 6]])

b

array([[0, 1, 2],
       [4, 5, 6]])

In [6]:
b.ndim

2

In [7]:
b.shape

(2, 3)

In [22]:
len(b)  # returns the size of the first dimention

2

In [9]:
# 3-D arrays

c = np.array([[[0, 1, 2], [3, 4, 5], [6, 7, 8]]])

c

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [10]:
d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [11]:
c.ndim

3

In [12]:
d.ndim

3

In [13]:
c.shape

(1, 3, 3)

In [15]:
d.shape

(2, 2, 2)

In [16]:
len(c) # returns the size of the first dimention

1

In [17]:
len(d) # returns the size of the first dimention

2

**1.2 Functions for creating arrays**

In [49]:
# using arange function 

# arange is an array-valued version of built-in python range function

a = np.arange(10) # 0 ....... n-1

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
b = np.arange(1, 10, 2) # start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [55]:
# using linspace (liear space)
# Creating a list of size 6 with the equal no of space within 1

a = np.linspace(0, 1, 6) # start, end, number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [56]:
# Common Arrays
# passing tuple of number

a = np.ones((3, 3)) 

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#  passing tuple of number
b = np.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
# Identity Matrix
# A matrix whose diagonal element is 1 and rest all elements are 0 called identity matrix
# Diagonally top left to bottom right

np.eye(3) # Returns a 2-D array with ones on the diagonal and zeros elsewhere


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.eye(3, 2) # 3 is the no. of rows, and 2 is the no. of columns,

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [66]:
# Create array using diag function

a = np.diag([1, 2, 3, 4]) # construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [67]:
np.diag(a) # Extract diagonal

array([1, 2, 3, 4])

In [21]:
# Create array using random
# Uniform Random

# Create an array of the given shape and populate it with random samples from a
a = np.random.rand(4)

a

array([0.46113822, 0.59545452, 0.82670353, 0.44441369])

In [23]:
# randn -> rand normal
# Standard Random

a = np.random.randn(4) # Returns a sample (or samples) from the standard normal variable

a

array([-0.05945052,  1.16466909,  0.17520495,  0.77009889])

**Note:**

     For random samples from N(\mu, \sigma^2), use:
     sigma * np.random.rand(...) + mu

# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used

In [76]:
a = np.arange(10)

a.dtype

dtype('int32')

In [87]:
# You can explicitly specify which data type you want:

a = np.arange(10, dtype='float64')

print(a)

a.dtype

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float64')

In [88]:
# The default data type is float for 'zeros' and 'ones' function

a = np.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [90]:
d = np.array([1+2j, 2+4j]) # Complex datatype

print(d.dtype)

complex128


In [93]:
b = np.array([True, False, True, False]) # Booolean datatype

print(b.dtype)

bool


In [95]:
s = np.array(['Arman', 'Madhur', 'Rusia'])

s.dtype

dtype('<U6')

# Each built-in data type has a character code that uniquely identifies it.

'?' -- boolean

'b' -- (signed) byte

'B' -- unsigned byte

'i' -- (signed) integer

'u' -- unsigned integer

'f' -- floating-point

'c' -- complex-floating point

'm' -- timedelta

'M' -- datetime

'O' -- (Python) objects

'S', 'a' -- zero-terminated bytes (not recommended)

'U' -- Unicode string

'V' -- raw data (void)

**For more details**

https://numpy.org/doc/stable/reference/arrays.dtypes.html



# 3. Indexing and Slicing 

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**

In [98]:
a = np.arange(10)

print(a[5]) # indices begin at 0, like other python sequences (and c/c++)

5


In [103]:
# For multidimentional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 4])

print(a[2, 2])

4


In [104]:
a[2, 1] = 5 # assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 4]])

**3.2 Slicing**

In [106]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
a[1:8:2]  # [startIndex: endIndex (exclusive): step]

array([1, 3, 5, 7])

In [108]:
# We can also combine assignment and slicing 

a = np.arange(10)

a[5:] = 10

a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [109]:
b = np.arange(5)

a[5:] = b[::-1] #assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# 4. Copies and views

A slicing operation created a view on the original array, which is just a way of accessing array data. Thus, the original array is not copied in memory. You can use **np.shares_memory()** to check if two arrays share the same memory block.

**When modifying the view, the original array is modified as well:**

In [26]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
b = a[::2]

b

array([0, 2, 4, 6, 8])

In [28]:
# Checking whether both are pointing to the same memory location or not
np.shares_memory(a, b)

True

In [29]:
b[0] = 10

b

array([10,  2,  4,  6,  8])

In [30]:
# 'a' and 'b' are pointing to the same memory location
a            # eventhough we modified 'b', but it updated 'a' also because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [31]:
a = np.arange(10)

c = a[::2].copy()  # force a copy

c

array([0, 2, 4, 6, 8])

In [32]:
np.shares_memory(a, c)

False

In [33]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5. Fancy Indexing

NumPy array can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Masks**

In [35]:
# Given range between 0 to 20
# total elements is given 15
a = np.random.randint(0, 20, 15)

a

array([ 5,  3,  4, 13, 16,  9, 10, 17,  4, 15, 17,  4,  3,  0, 15])

In [36]:
mask = (a % 2 == 0)

In [37]:
# Remove even values from the array
extract_from_a = a[mask]

extract_from_a

array([ 4, 16, 10,  4,  4,  0])

**Indexing with a mask can be very useful to assign a new value to a subarray**

In [38]:
# assign '-1' to all the even values
a[mask] = -1

a

array([ 5,  3, -1, 13, -1,  9, -1, 17, -1, 15, 17, -1,  3, -1, 15])

**Indexing with an array of integers**

In [39]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
# Indexing can be done with an array of integers, where the same index is repeatable
a[[2, 3, 2, 3, 2]]

array([20, 30, 20, 30, 20])

In [141]:
# New values can be assigned 

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])